### ISSUE TITLE
.mustache?

### ISSUE THREAD

**Issue by rickcolosimo** [seriesnext/seriesnext#62]
investment-agreement.mustache

Is that supposed to be .commonform? I'm admittedly way way behind on grokking all the changes related to the switchover, but just now as I was looking for the document, this one confused me since the other two filenames use".commonform" as terminators.

**Comment by kemitchell** [comment]
Mustache is a templating language. Basically, it lets you write very simple if-else and for-while bits in plain text files:

https://mustache.github.io/

There are a few such loops in the investment agreement for creating lists of purchase, key holders, and capitalization disclosures automatically from variables.json.
